name: design-baselines
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
dependencies:
- python>=3.7,<3.8
- pip>=20.0
- conda>=4.7
- cudatoolkit=10.1
- cudnn=7.6
- rdkit
- pip:
    - -r ./requirements.txt
    - -i https://pypi.tuna.tsinghua.edu.cn/simple